infocorp_affemat_homepage:
    pattern:  /
    defaults: { _controller: InfocorpAffematBundle:Home:index }

infocorp_affemat_noticias:
    pattern: /noticias
    defaults: { _controller: InfocorpAffematBundle:News:index }

infocorp_affemat_noticia:
    pattern: /noticias/{slug}
    defaults: { _controller: InfocorpAffematBundle:News:view }

infocorp_affemat_noticias_categoria:
    pattern: /noticias/categoria/{slug}
    defaults: { _controller: InfocorpAffematBundle:News:category }

infocorp_affemat_fale_conosco:
    pattern: /fale-conosco
    defaults: { _controller: InfocorpAffematBundle:Contact:email }

infocorp_affemat_slider:
    path: /slide
    defaults: { _controller: InfocorpAffematBundle:Slide:index }
