infocorp_affemat_homepage:
    pattern:  /
    defaults: { _controller: InfocorpAffematBundle:Home:index }

infocorp_affemat_noticias:
    pattern: /noticias
    defaults: { _controller: InfocorpAffematBundle:News:index }

infocorp_affemat_noticia:
    pattern: /noticias/{slug}
    defaults: { _controller: InfocorpAffematBundle:News:view }

infocorp_affemat_noticias_list_home:
    path: /noticias-list-home
    defaults: { _controller: InfocorpAffematBundle:News:homeList }

infocorp_affemat_noticias_categoria:
    pattern: /noticias/categoria/{slug}
    defaults: { _controller: InfocorpAffematBundle:News:category }

infocorp_affemat_fale_conosco:
    pattern: /fale-conosco
    defaults: { _controller: InfocorpAffematBundle:Contact:email }

infocorp_affemat_slider:
    path: /slide
    defaults: { _controller: InfocorpAffematBundle:Slide:index }

infocorp_affemat_institutional_list:
    path: /institucional-list
    defaults: { _controller: InfocorpAffematBundle:Institutional:list }

infocorp_affemat_institutional_view:
    pattern: /institucional/{slug}
    defaults: { _controller: InfocorpAffematBundle:Institutional:view }

infocorp_affemat_galeria:
    pattern: /galerias
    defaults: { _controller: InfocorpAffematBundle:Gallery:index }

infocorp_affemat_galeria_view:
    pattern: /galerias/{id}
    defaults: { _controller: InfocorpAffematBundle:Gallery:view }

infocorp_affemat_event_list:
    pattern: /eventos
    defaults: { _controller: InfocorpAffematBundle:Event:list }

infocorp_affemat_event_view:
    pattern: /eventos/{slug}
    defaults: { _controller: InfocorpAffematBundle:Event:view }