infocorp_affemat_homepage:
    pattern:  /
    defaults: { _controller: InfocorpAffematBundle:Default:index }

infocorp_affemat_noticias:
    pattern: /noticias
    defaults: { _controller: InfocorpAffematBundle:News:index }

infocorp_affemat_noticia:
    pattern: /noticias/{slug}
    defaults: { _controller: InfocorpAffematBundle:News:noticia }

infocorp_affemat_fale_conosco:
    pattern: /fale-conosco
    defaults: { _controller: InfocorpAffematBundle:Contact:email }