infocorp_affemat_homepage:
    pattern:  /
    defaults: { _controller: InfocorpAffematBundle:Default:index }

infocorp_affemat_noticias:
    pattern: /noticias
    defaults: { _controller: InfocorpAffematBundle:Default:noticias }
