parameters:
#    infocorp_affemat.example.class: Infocorp\Bundle\AffematBundle\Example

services:
    sonata.admin.featured:
        class: Infocorp\Bundle\AffematBundle\Admin\FeaturedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Home, label: Destaques }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\Featured, 'SonataAdminBundle:CRUD']
