parameters:
#    infocorp_affemat.example.class: Infocorp\Bundle\AffematBundle\Example

services:
    sonata.admin.featured:
        class: Infocorp\Bundle\AffematBundle\Admin\FeaturedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Destaques }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\Featured, null]

    sonata.admin.institutional:
        class: Infocorp\Bundle\AffematBundle\Admin\InstitutionalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Institucional }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\Institutional, null]

    sonata.admin.contact.group:
        class: Infocorp\Bundle\AffematBundle\Admin\ContactGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contato, label: Grupos }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\ContactGroup, null]

    sonata.admin.contact:
        class: Infocorp\Bundle\AffematBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contato, label: Contatos }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\Contact, null]

    sonata.admin.event:
        class: Infocorp\Bundle\AffematBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Eventos, label: Eventos }
        arguments: [null, Infocorp\Bundle\AffematBundle\Entity\Event, null]