<?php

namespace Infocorp\Bundle\AffematBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findEvents()
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT e
            FROM Infocorp\Bundle\AffematBundle\Entity\Event e
            WHERE e.enabled = 1
            AND e.publicationStartsAt <= CURRENT_TIMESTAMP()
            ORDER BY e.publicationStartsAt DESC
        ');

        return $query->getResult();
    }

    public function findEventBySlug($slug)
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT e
            FROM Infocorp\Bundle\AffematBundle\Entity\Event e
            WHERE e.enabled = 1
            AND e.publicationStartsAt <= CURRENT_TIMESTAMP()
            AND e.slug = :slug
        ');

        $query
            ->setParameter('slug', $slug)
            ->setMaxResults(1)
        ;

        return $query->getSingleResult();
    }
}