<?php

namespace Infocorp\Bundle\AffematBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedRepository extends EntityRepository
{
}
